/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DynamicForm: (typeof import('./../components/DynamicForm/index.vue'))['default']
    FileUpload: (typeof import('./../components/DynamicForm/FileUpload.vue'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
    VirtualList: (typeof import('./../components/VirtualList/index.vue'))['default']
  }
}
